image:
- Visual Studio 2017

platform:
- x64

environment:
    matrix:
        - PYTHON: "C:\\Python36-%PLATFORM%"

install:
  - "%PYTHON%\\python.exe --version"
  - "%PYTHON%\\python.exe -m pip install --upgrade pip wheel"
  - "%PYTHON%\\python.exe -c \"import wheel.pep425tags as w; print(w.get_supported())\""
  - "%PYTHON%\\python.exe -m pip install pythran-openblas"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install numpy"
  - "%PYTHON%\\python.exe -m pip install pytest"
  - "%PYTHON%\\python.exe -m pip install flake8"

build_script:
    - "%PYTHON%\\python.exe setup.py build"

test_script:
    - set PYTHONPATH=.
    - "%PYTHON%\\python.exe -m pytest pythran/tests/test_scipy.py -v"
    - "%PYTHON%\\python.exe -m pytest pythran/tests/test_base.py -v"
    - "%PYTHON%\\python.exe -m pytest pythran/tests/test_advanced.py -v"
    - "%PYTHON%\\python.exe -m flake8 pythran/*.py pythran/*/*.py --exclude='pythran/tests/test*.py,__init__.py'"
